name: Test SteamCMD Branch
on:
  push:
    branches: steamcmd
  
    
jobs:
  job_id: 
   name: SteamCMD Build Check
   runs-on: [ubuntu-latest]
   timeout-minutes: 2
   
   steps:
   - name: Install SteamCMD
     run: |
          curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
              ./steamcmd.sh +login anonymous +exit
    
   - name: Set up Go 1.13.5
     uses: actions/setup-go@v1
     with:
      go-version: 1.13.5
      id: go

   - name: Check out code into the Go module directory
     uses: actions/checkout@v1

   - name: Get dependencies
     run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
   - name: Build
     run: go build -v .
